[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/*.epub"
  [headers.values]
    Content-Type = "application/epub+zip"
    Content-Disposition = "attachment"

[[headers]]
  for = "/*.pdf"
  [headers.values]
    Content-Type = "application/pdf"
    Content-Disposition = "attachment"
